---
version: "{build}"
clone_depth: 10
platform: x64
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem update --system
  - gem --version
  - gem install hoe minitest rake-compiler --no-document
build_script:
  - net user
  - net localgroup
  - cd ext\psych
  - ruby extconf.rb --enable-bundled-libyaml
test_script:
  - rake test
environment:
  matrix:
    - ruby_version: "21-x64"
    - ruby_version: "22-x64"
